/**
 * Write dist/sw.js with a precache list of everything the map needs offline.
 *
 * Runs after `vite build` (see the build script in package.json). Vite hashes
 * asset filenames, so the list has to be generated from the real output rather
 * than written by hand -- a hand-kept list goes stale silently, and a stale
 * precache is worse than none.
 *
 * Why the festival needs this at all: Candler Park in October has ten thousand
 * people on the same few cell towers. The map has to open for someone standing
 * at the gate with one bar, and keep working once they are inside.
 */
import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, relative } from 'node:path';

const DIST = 'dist';

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

const all = walk(DIST).map((f) => '/' + relative(DIST, f).split(/[\\/]/).join('/'));

// What the map needs in a field with no signal. Deliberately NOT everything:
//   .woff      every browser we target takes woff2; the .woff files are emitted
//              beside them and never requested, so caching them would double
//              the font payload for nothing
//   design-system.html and its chunks
//              the style guide is a working tool, not part of the map
const skip = (f) => f.endsWith('.woff') || f.startsWith('/design-system') || f.includes('designSystem');
const precache = all.filter((f) => !skip(f)).sort();

// One version per set of contents. Change a file, get a new cache, and the old
// one is dropped on activate -- no stale asset can survive a deploy.
const version = createHash('sha256')
  .update(precache.map((f) => f + ':' + statSync(join(DIST, f.slice(1))).size).join('\n'))
  .digest('hex').slice(0, 12);

const bytes = precache.reduce((n, f) => n + statSync(join(DIST, f.slice(1))).size, 0);

const sw = `/* GENERATED by scripts/build-sw.mjs -- do not edit dist/sw.js by hand. */
const VERSION = '${version}';
const CACHE = 'fallfest-' + VERSION;
const PRECACHE = ${JSON.stringify(precache, null, 2)};

// ignoreVary is load-bearing, and it took a packet trace to find out why.
// The server sends "Vary: Origin" on everything. Precaching fetches these URLs
// with no Origin header; the browser then requests the module scripts and
// stylesheets with one, because Vite marks those tags crossorigin. Without
// ignoreVary the cache treats that as a different request and misses every JS
// and CSS file -- so the shell loads offline and the app never boots. A blank
// green screen at the festival gate, and nothing in the console but "failed to
// fetch". Every asset here is content-hashed and identical for all origins, so
// there is nothing Vary could usefully distinguish anyway.
const MATCH = { ignoreVary: true };

// Install: fetch the whole map into the cache before declaring victory. If any
// one file fails the install fails, so a half-cached map never goes live.
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

// Activate: drop every older version's cache, then take over the open pages.
self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('fallfest-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const { request } = e;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // The page itself: try the network briefly, fall back to the cached shell.
  // Network-first here is what lets a new deploy be seen at all; the timeout is
  // what stops one bar of signal from hanging the map on the festival green.
  if (request.mode === 'navigate') {
    e.respondWith(
      Promise.race([
        fetch(request).then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put('/index.html', copy));
          return res;
        }),
        new Promise((resolve) => setTimeout(() => resolve(caches.match('/index.html', MATCH)), 2500)),
      ]).catch(() => caches.match('/index.html', MATCH)),
    );
    return;
  }

  // Everything else is content-hashed, so a cache hit is always correct.
  e.respondWith(
    caches.match(request, MATCH).then((hit) => hit || fetch(request).then((res) => {
      if (res.ok && res.type === 'basic') {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(request, copy));
      }
      return res;
    })),
  );
});
`;

writeFileSync(join(DIST, 'sw.js'), sw);
console.log(`wrote dist/sw.js — ${precache.length} files, ${(bytes / 1024).toFixed(0)}KB precached, version ${version}`);
console.log(`  skipped ${all.length - precache.length} (legacy .woff + the style guide)`);
