#!/usr/bin/env python3
"""Regenerate the favicon SVGs from the real display font.

    python3 scripts/build-icon.py                                   # public/favicon.svg, from Brice-Black
    python3 scripts/build-icon.py Brice-SemiBold scripts/favicon-small.svg   # lighter cut, for 32px
    node scripts/build-icon.mjs                                     # then the PNGs, from those SVGs

The FF has to BE Manrope ExtraBold, not a drawing of it -- it is the masthead's
face, and the icon is the masthead at 16px. An SVG favicon cannot rely on a
webfont being available (favicons render in a restricted context), so the glyphs
ship as geometry; this pulls that geometry out of the same font file the app
loads, @fontsource/manrope's 800 weight, rather than approximating the shapes.

Rerun it if the masthead's face ever changes.
"""
import os
import re
import sys
from fontTools.ttLib import TTFont
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen

# The masthead's face, in preference order -- the icon is the masthead at 16px,
# so it follows whatever --font-display resolves to. Brice is the brand face;
# Manrope is what ships until Brice's files are licensed and dropped into
# src/assets/fonts (see the README there). First one present wins.
ARG_FACE = sys.argv[1] if len(sys.argv) > 1 else None
ARG_OUT = sys.argv[2] if len(sys.argv) > 2 else None

CANDIDATES = [
    'src/assets/fonts/%s.otf' % ARG_FACE if ARG_FACE else 'src/assets/fonts/Brice-Black.otf',
    'src/assets/fonts/Brice-Bold.otf',
    'src/assets/fonts/Brice-SemiBold.otf',
    'node_modules/@fontsource/manrope/files/manrope-latin-800-normal.woff2',
]
OUT = ARG_OUT or 'public/favicon.svg'
BOX = 64        # icon viewBox
INK_W = 80.0    # how wide the FF pair is -- WIDER THAN THE ICON, on purpose
CAP_MAX = 44.0  # ...but never taller than this

# Fit by WIDTH, not by cap height -- Brice Black is a much wider face than
# Manrope, so a cap height that suits one fills the icon edge to edge in the
# other. Deriving the scale from the pair's inked width keeps the mark the same
# size whatever face the masthead is using.
#
# And the width is deliberately larger than the icon. The FF bleeds off both
# sides and is clipped by the tile, the way a map is a crop of somewhere bigger
# rather than a diagram sitting on a card. Sized so the stems are cut but the
# arms are whole: you still read FF instantly, it just refuses to sit politely
# inside its box.

SRC = next((p for p in CANDIDATES if os.path.exists(p)), None)
if SRC is None:
    raise SystemExit('No display font found. Looked for:\n  ' + '\n  '.join(CANDIDATES))

f = TTFont(SRC)
gs = f.getGlyphSet()
g = f.getBestCmap()[ord('F')]
adv = f['hmtx'][g][0]
cap = getattr(f['OS/2'], 'sCapHeight', None) or f['head'].unitsPerEm * 0.72

# Glyph bounds: TrueType keeps them on the glyph, CFF (.otf) does not, so measure
# the outline instead. Brice ships as .otf, so this branch is not hypothetical.
if 'glyf' in f:
    gl = f['glyf'][g]
    x_min, x_max = gl.xMin, gl.xMax
else:
    bp = BoundsPen(gs)
    gs[g].draw(bp)
    x_min, x_max = bp.bounds[0], bp.bounds[2]


class _BB:
    pass


bb = _BB()
bb.xMin, bb.xMax = x_min, x_max

ink_units = adv + bb.xMax - bb.xMin          # inked width of the pair, in font units
s = min(INK_W / ink_units, CAP_MAX / cap)   # whichever constraint binds first
cap_px = cap * s
ink_l, ink_r = bb.xMin * s, adv * s + bb.xMax * s
x0 = (BOX - (ink_r - ink_l)) / 2 - ink_l    # centre on the INK, not on the advance
y0 = (BOX + cap_px) / 2                     # baseline, cap height centred in the box


def tidy(d):
    return re.sub(r'-?\d+\.?\d*', lambda m: ('%.2f' % float(m.group())).rstrip('0').rstrip('.'), d)


paths = []
for i in range(2):
    pen = SVGPathPen(gs)
    gs[g].draw(TransformPen(pen, (s, 0, 0, -s, x0 + i * adv * s, y0)))
    paths.append(tidy(pen.getCommands()))

svg = '''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {box} {box}" role="img" aria-label="Fall Fest map">
  <!-- GENERATED by scripts/build-icon.py -- do not hand-edit the paths.

       Ground: the map's own park green, so the icon reads as a piece of the map.
       The streets run above and below the letters, hard against the edges, and
       never through them: a pale band across an F's arms closes it up and the
       pair starts reading as PP -- and at 32px a band merely NEAR the arms does
       the same, because antialiasing closes the gap for you.

       The FF is {face}'s own F, twice, taken from the font file the app
       loads. See the module docstring for why it ships as geometry. -->
  <defs>
    <clipPath id="tile"><rect width="{box}" height="{box}" rx="13"/></clipPath>
  </defs>
  <g clip-path="url(#tile)">
    <rect width="{box}" height="{box}" fill="#ADD29E"/>
    <g fill="#E1E6EB" opacity="0.65">
      <rect x="-6" y="2" width="76" height="5"/>
      <rect x="-6" y="57" width="76" height="5"/>
      <rect x="-26" y="-2" width="48" height="4.5" transform="rotate(-36 7 7)"/>
      <rect x="43" y="-8" width="4.5" height="16"/>
    </g>
    <g fill="#23385B">
      <path d="{a}"/>
      <path d="{b}"/>
    </g>
  </g>
</svg>
'''.format(box=BOX, a=paths[0], b=paths[1], face=f['name'].getDebugName(4) or 'the display face')

open(OUT, 'w').write(svg)
face = f['name'].getDebugName(4) or os.path.basename(SRC)
print('wrote %s -- %s, F x2, %.1f wide x %.1f tall in a %d box' % (OUT, face, ink_r - ink_l, cap_px, BOX))
print('  source: %s' % SRC)
