#!/usr/bin/env python3
"""Regenerate public/favicon.svg and the PNG icons from the real Manrope file.

    python3 scripts/build-icon.py        # SVG only
    node scripts/build-icon.mjs          # then the PNGs, from that SVG

The FF has to BE Manrope ExtraBold, not a drawing of it -- it is the masthead's
face, and the icon is the masthead at 16px. An SVG favicon cannot rely on a
webfont being available (favicons render in a restricted context), so the glyphs
ship as geometry; this pulls that geometry out of the same font file the app
loads, @fontsource/manrope's 800 weight, rather than approximating the shapes.

Rerun it if the masthead's face ever changes.
"""
import re
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen

SRC = 'node_modules/@fontsource/manrope/files/manrope-latin-800-normal.woff2'
OUT = 'public/favicon.svg'
BOX = 64        # icon viewBox
CAP = 30.0      # cap height inside it

f = TTFont(SRC)
gs = f.getGlyphSet()
g = f.getBestCmap()[ord('F')]
adv = f['hmtx'][g][0]
cap = f['OS/2'].sCapHeight
bb = f['glyf'][g]

s = CAP / cap
ink_l, ink_r = bb.xMin * s, adv * s + bb.xMax * s
x0 = (BOX - (ink_r - ink_l)) / 2 - ink_l    # centre on the INK, not on the advance
y0 = (BOX + CAP) / 2                        # baseline, cap height centred in the box


def tidy(d):
    return re.sub(r'-?\d+\.?\d*', lambda m: ('%.2f' % float(m.group())).rstrip('0').rstrip('.'), d)


paths = []
for i in range(2):
    pen = SVGPathPen(gs)
    gs[g].draw(TransformPen(pen, (s, 0, 0, -s, x0 + i * adv * s, y0)))
    paths.append(tidy(pen.getCommands()))

svg = '''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {box} {box}" role="img" aria-label="Fall Fest map">
  <!-- GENERATED by scripts/build-icon.py -- do not hand-edit the paths.

       Ground: the map's own park green, so the icon reads as a piece of the map.
       The streets sit clear of the letters: one down the left edge, one along
       the bottom, and the diagonal at the angle the car path actually runs.

       The FF is Manrope ExtraBold's own F, twice, taken from the font file the
       app loads. See the module docstring for why it ships as geometry. -->
  <rect width="{box}" height="{box}" rx="13" fill="#ADD29E"/>
  <g fill="#E1E6EB" opacity="0.6">
    <rect x="-8" y="18" width="80" height="5.5" transform="rotate(-36 32 32)"/>
    <rect x="3" y="-6" width="6" height="76"/>
    <rect x="-6" y="52" width="76" height="6"/>
  </g>
  <g fill="#23385B">
    <path d="{a}"/>
    <path d="{b}"/>
  </g>
</svg>
'''.format(box=BOX, a=paths[0], b=paths[1])

open(OUT, 'w').write(svg)
print('wrote %s -- Manrope ExtraBold F x2, cap %.0f in a %d box' % (OUT, CAP, BOX))
