import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
// Latin only. The unscoped imports pull every subset @fontsource ships --
// cyrillic, greek, vietnamese, latin-ext -- which came to 120KB of glyphs this
// map will never render, on top of 300KB of legacy .woff nothing we target
// still needs. That is a lot to ask of a phone on festival wifi, and a lot to
// hold in an offline cache.
//
// 800 is --weight-black: the masthead, panel titles, day headings. Without it
// the browser synthesises a fake bold off 700, and every platform fakes it
// differently -- which is why the title looked wrong on desktop but fine on iOS.
import '@fontsource/manrope/latin-400.css'
import '@fontsource/manrope/latin-500.css'
import '@fontsource/manrope/latin-600.css'
import '@fontsource/manrope/latin-700.css'
import '@fontsource/manrope/latin-800.css'
import './styles/global.css'
import App from './App.jsx'

// The map has to work at the gate, where ten thousand people share a few cell
// towers. The service worker (generated by scripts/build-sw.mjs) holds the whole
// map -- shell, fonts, icons, basemap -- so a second visit needs no network at
// all. Production only: in dev it would serve yesterday's bundle back to you.
if (import.meta.env.PROD && 'serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/sw.js').catch(() => {
      // No offline map is a worse map, not a broken one. Nothing to tell the user.
    });
  });
}

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
